version: "3.8"
services:
  oddmatrix-client:
    build: .
    volumes:
      - oddmatrix-client-logs:/app/logs
    networks:
      - oddmatrix-client-network
volumes:
  oddmatrix-client-logs:
    name: oddmatrix-client-logs

networks:
  oddmatrix-client-network:
