version: "3.8"
services:
  oddmatrix-client:
    container_name: oddmatrix-client
    build:
      context: .
      dockerfile: Dockerfile
    image: oddmatrix-client:${TAG:-latest}
    volumes:
      - oddmatrix-client-logs:/application/logs
    network_mode: "host"
volumes:
  oddmatrix-client-logs:
    name: oddmatrix-client-logs
